### ISSUE TITLE
Mod errors - UnCiv 4.6.19 (Build 877)

### ISSUE THREAD

**Issue by carloshcosta** [SpacedOutChicken/Resource-Recyclers#3]
Biofuel Farm's unique "Provides [1] [Coal]" contains parameter Coal, which does not fit parameter type resource !
Biofuel Farm's unique "Provides [1] [Oil]" contains parameter Oil, which does not fit parameter type resource !
Ore Refinery's unique "Provides [1] [Aluminum]" contains parameter Aluminum, which does not fit parameter type resource !
Ore Refinery's unique "Provides [1] [Uranium]" contains parameter Uranium, which does not fit parameter type resource !

**Comment by SpacedOutChicken** [comment]
I think these errors are the result of using the mod checker with using a base ruleset to check the extension mods. Select either Vanilla or Gods & Kings Civ V as the ruleset, and you'll see the errors disappear.
